Desktop/Workspace/MusicCollection/MusicCollection/Models/Genero.cs
using System.ComponentModel.DataAnnotations;

namespace MusicCollection.Models
{
    public class Genero
    {
        public int Id { get; set; }
        public string Nombre { get; set; }

        [Display(Name ="Descripción")]        
        public string? Descripcion { get; set; }

        [Display(Name = "Fecha Creación")]
        [DataType(DataType.Date)]
        public DateTime FechaCreacion { get; set; }
        public string? Icono { get; set; } 
    }
}

Desktop/Workspace/MusicCollection/MusicCollection/Models/GeneroViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MusicCollection.Models
{
    public class GeneroViewModel
    {
        public List<Genero>? Generos { get; set; }
        public SelectList? ListaGeneros { get; set; }
        public string? FiltroGenero { get; set; }
        public string? Busqueda { get; set; }
    }
}

Desktop/Workspace/MusicCollection/MusicCollection/Controllers/GenerosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicCollection.Data;
using MusicCollection.Models;

namespace MusicCollection.Controllers
{
    public class GenerosController : Controller
    {
        private readonly MusicCollectionContext _context;

        public GenerosController(MusicCollectionContext context)
        {
            _context = context;
        }

        // GET: Generos
        public async Task<IActionResult> Index(string busqueda)
        {
            //poblar los generos de musica
            var generosLista = from g in _context.Generos
                               select g.Nombre;

            //forma sin validacion
            //investigar que es LINQ
            var generos = from g in _context.Generos
                          select g;

            //filtramos los datos de acuerdo con el string busqueda
            if(!String.IsNullOrEmpty(busqueda))
            {
                generos = generos.Where(g => g.Descripcion.Contains(busqueda));
            }

            var generoVM = new GeneroViewModel
            {
                Generos = await generos.ToListAsync(),
                ListaGeneros = new SelectList(await generosLista.ToListAsync())
            };
            //retornamos los valores
            return View(generoVM);
        }

        // GET: Generos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Generos == null)
            {
                return NotFound();
            }

            var genero = await _context.Generos.FirstOrDefaultAsync(m => m.Id == id);
            if (genero == null)
            {
                return NotFound();
            }

            return View(genero);
        }

        // GET: Generos/Create
        [HttpGet] // no hay que  para hacer un get
        public IActionResult Create()
        {
            return View();
        }

        // POST: Generos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Descripcion,FechaCreacion,Icono")] Genero genero)
        {
            if (ModelState.IsValid)
            {
                _context.Add(genero);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(genero);
        }

        // GET: Generos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Generos == null)
            {
                return NotFound();
            }

            var genero = await _context.Generos.FindAsync(id);
            if (genero == null)
            {
                return NotFound();
            }
            return View(genero);
        }

        // POST: Generos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Descripcion,FechaCreacion,Icono")] Genero genero)
        {
            if (id != genero.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(genero);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GeneroExists(genero.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(genero);
        }

        // GET: Generos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Generos == null)
            {
                return NotFound();
            }

            var genero = await _context.Generos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (genero == null)
            {
                return NotFound();
            }

            return View(genero);
        }

        // POST: Generos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Generos == null)
            {
                return Problem("Entity set 'MusicCollectionContext.Generos'  is null.");
            }
            var genero = await _context.Generos.FindAsync(id);
            if (genero != null)
            {
                _context.Generos.Remove(genero);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GeneroExists(int id)
        {
          return (_context.Generos?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Desktop/Workspace/MusicCollection/MusicCollection/Views/Generos/Create.cshtml
@model MusicCollection.Models.Genero

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Genero</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaCreacion" class="control-label"></label>
                <input asp-for="FechaCreacion" class="form-control" />
                <span asp-validation-for="FechaCreacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Icono" class="control-label"></label>
                <select asp-for="Icono" class="form-select">
                    <option value="bi bi-boombox">Boombox<i class="bi bi-boombox"></i></option>
                    <option value="bi bi-cassette">Cassette</option>
                    <option value="bi bi-file-music">File Music</option>
                    <option value="bi bi-music-player">Music Player</option>
                    <option value="bi bi-vinyl">Vinyl</option>
                </select>
                <span asp-validation-for="Icono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Desktop/Workspace/MusicCollection/MusicCollection/Views/Generos/Delete.cshtml
@model MusicCollection.Models.Genero

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Genero</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaCreacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaCreacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Icono)
        </dt>
        <dd class = "col-sm-10">
            <i class="@Model.Icono" style="font-size: 1.5em;"></i>
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Desktop/Workspace/MusicCollection/MusicCollection/Views/Generos/Details.cshtml
@model MusicCollection.Models.Genero

@{
    ViewData["Title"] = "Detalles";
}

<h1>Detalles</h1>

<div>
    <h4>Genero</h4>
    <hr />
   
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaCreacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaCreacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Icono)
        </dt>
        <dd class = "col-sm-10">
            <i class="@Model.Icono" style="font-size: 1.5em;"></i>
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-success">Edit</a> |
    <a asp-action="Index" class="btn btn-primary">Back to List</a>
</div>

Desktop/Workspace/MusicCollection/MusicCollection/Views/Generos/Edit.cshtml
@model MusicCollection.Models.Genero

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Genero</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label" style="color: red"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaCreacion" class="control-label"></label>
                <input asp-for="FechaCreacion" class="form-control" />
                <span asp-validation-for="FechaCreacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Icono" class="control-label"></label>
                <select asp-for="Icono" class="form-select">
                    <option value="bi bi-boombox">Boombox<i class="bi bi-boombox"></i></option>
                    <option value="bi bi-cassette">Cassette</option>
                    <option value="bi bi-file-music">File Music</option>
                    <option value="bi bi-music-player">Music Player</option>
                    <option value="bi bi-vinyl">Vinyl</option>
                </select>
                <i class="@Model.Icono"></i>
                <span asp-validation-for="Icono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Desktop/Workspace/MusicCollection/MusicCollection/Views/Generos/Index.cshtml
@model MusicCollection.Models.GeneroViewModel

@{
    ViewData["Title"] = "Índice";
}

<h1>Indice</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Crear</a>
</p>

<form asp-controller="Generos">
    <p>Genero: </p>
    <input type="text" asp-for="Busqueda"/>

    <select asp-for="FiltroGenero" asp-items="Model.ListaGeneros">
        <option value="">Todos</option>
    </select>

    <button type="submit" class="btn btn-primary btn-sm">Buscar</button>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Generos[0].Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Generos[0].Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Generos[0].FechaCreacion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Generos) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaCreacion)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-success">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-primary">Detalles</a> |
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>