Desktop/Workspace/MusicCollection/MusicCollection/Models/Musica.cs
using System.ComponentModel.DataAnnotations;

namespace MusicCollection.Models
{
    public class Musica
    {
        [Key]
        public int Id { get; set; }
        [Required (ErrorMessage = "Debe ingresar un nombre de artista")]
        public string Artista { get; set; }
        [Display(Name ="Título")]

        [Required(ErrorMessage = "Debe especificar un título")]
        [StringLength(100, MinimumLength = 3, ErrorMessage = "Debe especificar al menos tres caracteres")]
        public string Titulo { get; set; }
        [Range(1700, 2099, ErrorMessage = "Debe especificar un rango entre 1700 y 2099")]
        [Display(Name = "Año")]
        public int Ano { get; set; }
        [RegularExpression(@"^[A-Z]+[a-zA-Z\s]*$", ErrorMessage = "Solo letras")]
        [Required]
        public string Formato { get; set; }
        public int GeneroId { get; set; }
        public virtual Genero? Genero { get; set; }
    }
}

Desktop/Workspace/MusicCollection/MusicCollection/Models/MusicaViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MusicCollection.Models
{
    public class MusicaViewModel
    {
        public List<Musica>? Musica { get; set; }
        public SelectList? ListaGeneros { get; set; }
        public int? FiltroGenero { get; set; }
        public string? Busqueda { get; set; }

    }
}

Desktop/Workspace/MusicCollection/MusicCollection/Models/ResumenViewModel.cs
namespace MusicCollection.Models
{
    public class ResumenViewModel
    {
        public string Genero { get; set; }
        public int Cantidad { get; set; }
    }
}

Desktop/Workspace/MusicCollection/MusicCollection/Controllers/MusicasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicCollection.Data;
using MusicCollection.Models;

namespace MusicCollection.Controllers
{
    public class MusicasController : Controller
    {
        private readonly MusicCollectionContext _context;

        public MusicasController(MusicCollectionContext context)
        {
            _context = context;
        }

        // GET: Musicas
        public async Task<IActionResult> Index(string busqueda,int? FiltroGenero )
        {
            var musicCollectionContext = from t in _context.Musica.Include(m => m.Genero)
                                         select t;
            var generos = new SelectList(_context.Generos, "Id", "Nombre");

            if (!String.IsNullOrEmpty(busqueda))
            {
                musicCollectionContext = musicCollectionContext.Where(n => n.Artista.Contains(busqueda));
            }

            if(FiltroGenero != null)
            {
                musicCollectionContext = musicCollectionContext.Where(n => n.GeneroId == FiltroGenero);
            }

            var musicaVM = new MusicaViewModel
            {
                Musica = await musicCollectionContext.ToListAsync(),
                ListaGeneros = generos
            };
            return View(musicaVM);
        }

        // GET: Musicas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Musica == null)
            {
                return NotFound();
            }

            var musica = await _context.Musica
                .Include(m => m.Genero)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (musica == null)
            {
                return NotFound();
            }

            return View(musica);
        }

        // GET: Musicas/Create
        public IActionResult Create()
        {
            ViewData["GeneroId"] = new SelectList(_context.Generos, "Id", "Nombre");
            return View();
        }

        // POST: Musicas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Artista,Titulo,Ano,Formato,GeneroId")] Musica musica)
        {
            if (ModelState.IsValid)
            {
                _context.Add(musica);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GeneroId"] = new SelectList(_context.Generos, "Id", "Id", musica.GeneroId);
            return View(musica);
        }

        // GET: Musicas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Musica == null)
            {
                return NotFound();
            }

            var musica = await _context.Musica.FindAsync(id);
            if (musica == null)
            {
                return NotFound();
            }
            ViewData["GeneroId"] = new SelectList(_context.Generos, "Id", "Nombre", musica.GeneroId);
            return View(musica);
        }

        // POST: Musicas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Artista,Titulo,Ano,Formato,GeneroId")] Musica musica)
        {
            if (id != musica.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(musica);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MusicaExists(musica.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GeneroId"] = new SelectList(_context.Generos, "Id", "Id", musica.GeneroId);
            return View(musica);
        }

        // GET: Musicas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Musica == null)
            {
                return NotFound();
            }

            var musica = await _context.Musica
                .Include(m => m.Genero)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (musica == null)
            {
                return NotFound();
            }

            return View(musica);
        }

        // POST: Musicas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Musica == null)
            {
                return Problem("Entity set 'MusicCollectionContext.Musica'  is null.");
            }
            var musica = await _context.Musica.FindAsync(id);
            if (musica != null)
            {
                _context.Musica.Remove(musica);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Resumen()
        {
            // busco todos los generos
            var generos = await _context.Generos.ToListAsync();
            if(generos.Count == 0)
            {
                return NotFound();
            }

            List<ResumenViewModel> resumen = new List<ResumenViewModel>();

            foreach(var genero in generos)
            {
                var cantidad = _context.Musica.
                                Where(g => g.GeneroId == genero.Id)
                                .Count();

                resumen.Add(new ResumenViewModel
                {
                    Genero = genero.Descripcion,
                    Cantidad = cantidad
                });
            }

            return View(resumen); 
        }
        private bool MusicaExists(int id)
        {
            return (_context.Musica?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Desktop/Workspace/MusicCollection/MusicCollection/Views/Musicas/Create.cshtml
@model MusicCollection.Models.Musica

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Musica</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Artista" class="control-label"></label>
                <input asp-for="Artista" class="form-control" />
                <span asp-validation-for="Artista" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ano" class="control-label"></label>
                <input asp-for="Ano" class="form-control" />
                <span asp-validation-for="Ano" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Formato" class="control-label"></label>
                <input asp-for="Formato" class="form-control" />
                <span asp-validation-for="Formato" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GeneroId" class="control-label"></label>
                <select asp-for="GeneroId" class ="form-select" asp-items="ViewBag.GeneroId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Desktop/Workspace/MusicCollection/MusicCollection/Views/Musicas/Delete.cshtml
@model MusicCollection.Models.Musica

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Musica</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Artista)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Artista)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ano)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ano)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Formato)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Formato)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Desktop/Workspace/MusicCollection/MusicCollection/Views/Musicas/Details.cshtml
@model MusicCollection.Models.Musica

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Musica</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Artista)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Artista)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ano)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ano)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Formato)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Formato)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Desktop/Workspace/MusicCollection/MusicCollection/Views/Musicas/Edit.cshtml
@model MusicCollection.Models.Musica

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Musica</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Artista" class="control-label"></label>
                <input asp-for="Artista" class="form-control" />
                <span asp-validation-for="Artista" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ano" class="control-label"></label>
                <input asp-for="Ano" class="form-control" />
                <span asp-validation-for="Ano" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Formato" class="control-label"></label>
                <input asp-for="Formato" class="form-control" />
                <span asp-validation-for="Formato" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GeneroId" class="control-label"></label>
                <select asp-for="GeneroId" class="form-select" asp-items="ViewBag.GeneroId"></select>
                <span asp-validation-for="GeneroId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Desktop/Workspace/MusicCollection/MusicCollection/Views/Musicas/Index.cshtml
@model MusicCollection.Models.MusicaViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Musicas">
    <p>Artista: </p>
    <input type="text" asp-for="Busqueda"/>

    <select asp-for="FiltroGenero" asp-items="Model.ListaGeneros">
        <option value="">Todos</option>
    </select>
    <button type="submit" class="btn btn-primary btn-sm">Buscar</button>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Musica[0].Artista)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Musica[0].Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Musica[0].Ano)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Musica[0].Formato)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Musica[0].Genero)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Musica) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Artista)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ano)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Formato)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genero.Nombre)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Desktop/Workspace/MusicCollection/MusicCollection/Views/Musicas/Resumen.cshtml
@model IEnumerable<ResumenViewModel>
<h2>Resumen</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Genero</th>
            <th>Cantidad</th>
        </tr>
    </thead>
    <tbody>
        @{
            int total = 0;
        }
        @foreach(var gen in Model)
        {
            <tr>
                <td>@gen.Genero</td>
                <td>@gen.Cantidad</td>
                @{
                    total += gen.Cantidad; 
                }
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <th>Total Discos</th>
            <th>@total</th>
        </tr>
    </tfoot>
</table>